sudo: required
services:
  - docker

before_install:
  - docker build -t 8273/react-docker -f Dockerfile.dev .

script:
  - docker run 8273/react-docker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "react-docker"
  env: "ReactDocker-env"
  bucket_name: "elasticbeanstalk-us-east-1-853878734673"
  bucket_path: "react-docker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"